### PR TITLE
improving lizardfans.py functionality & tests support for Windows platform

### PR DESCRIPTION
**Pull request by mehrdad89**
adding support for overloading functions and reducing the execution time on lizardfans.py extension for
lizard_ext/lizardfans.py

### CODE REVIEW

**Comment by mehrdad89** [comment]
I just found out that your changes are also added in this pull request. hope it can be resolved by merging.

**Comment by mehrdad89** [comment]
I think I will do another pull request after we fix the other part of the code (nesting depth) and also I'm not proud of this upload. therefore, I'll close this one too.

**Comment by terryyin** [comment]
Hi Mehrdad,

Sorry for not helping last week. Both my kids had dental operations. Please slow down and do it piece by piece, it’s a journey:-)

br, Terry

**Comment by mehrdad89** [comment]
You are right.
I think we can talk about what we should do next. :relaxed:

**Pull request closed without merging**
