### PR TITLE
Nesting Depth

### PR DESCRIPTION
**Pull request by mehrdad89**
Introducing Maximum Nesting Depth for Clike and Python languages, which detects the maximum 'nestedness' (nesting for-loops, if-statements, etc.) in any source code without caring about the C/C++ header files or Python imports.

### CODE REVIEW

**Comment by mehrdad89** [comment]
I will try to fixed them as soon as possible. Sorry about that!

**Comment by terryyin** [comment]
Please take time:-)

**Comment by mehrdad89** [comment]
Thanks, I will fix the issues then I will send a pull request again.

**Comment by terryyin** [comment]
Hi @mehrdad89 , just to let you know that during the refactoring I had to revert your changes in the lizard_languages/python.py, because I found yielding a <indent> might not be a best way of handling it. And it breaks other feature as well.

I will bring it back probably with another solution after the refactoring.

**Comment by mehrdad89** [comment]
@terryyin Great, I'll be waiting eagerly to see what you can up with. I also faced another trouble regarding adding structural fan-in & fan-out. I am now looking to see how I can structural fan-in and fan-out at a local scope while having global scope in mind.

**Pull request closed without merging**
