### PR TITLE
Add C# test file #92

### PR DESCRIPTION
**Pull request by iconnor**
I know it is probably not that much help, but I hoped it would show we are keen for this feature. I took the example code from: https://msdn.microsoft.com/en-us/library/ms182212.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1

### CODE REVIEW

**Comment by terryyin** [comment]
Hi @iconnor thank you very much, I think this is very useful. I will be working on it soon, I think.

**Comment by terryyin** [comment]
Hi @iconnor , passing those tests turned out to be extremely easy, as C# syntax is very similar to C++. Now I'm looking into detailed C# syntax and see if there's any exception (I'm a lousy C# programmer myself).

I have a question regarding the CCN for C#. Should the Null Coalescing Operator (??) be counted as one condition? I'm guessing yes.

**Comment by iconnor** [comment]
As the alternative is an if null statement, I would vote yes on ?? increasing complexity. It is still something you have to think about when reading the method. Doing it on one line is neat but still a condition.

**Comment by terryyin** [comment]
Hi @iconnor ,
I've made a new release (1.11.0) with support for C#. Could you please test it a bit?

**Pull request merged**
