### PR TITLE
Update project (file fixes)

### PR DESCRIPTION
**Pull request by friederbluemle**
This PR does the following:

- Fix all whitespace errors in the repo (automated using pre-commit locally)
- Standardized all files to have `LF` line endings (Oddly, _three files_ had `CRLF` line endings)
- Fix a few pycodestyle warnings and errors
- Fix all remaining pylint and pytest errors

```
lizard_ext/csvoutput.py:22:80: E501 line too long (87 > 79 characters)
lizard_ext/csvoutput.py:35:62: E231 missing whitespace after ','
lizard_ext/csvoutput.py:41:58: E231 missing whitespace after ','
lizard_ext/csvoutput.py:42:63: E231 missing whitespace after ','
lizard_ext/version.py:5:1: W391 blank line at end of file
```

### CODE REVIEW

**Comment by friederbluemle** [comment]
Travis CI is passing again! 🎉 👍 

AppVeyor failure needs to be checked and fixed separately I assume.

```
E       WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmpfj6mmh'
test\test_auto_open.py:23: WindowsError
```

Also Travis CI build on macos is currently removed due to this error:

```
$ pip install -e .
/Users/travis/.travis/job_stages: line 57: pip: command not found
The command "pip install -e ." failed and exited with 127 during .
```

**Comment by terryyin** [comment]
Hi @friederbluemle thanks for the pull request. Everything looks great except default returns. I'm against adding production code without having any failing tests. And I guess it's impossible to add any test to justify these returns. Can we agree to remove them?

**Comment by friederbluemle** [comment]
Hi @terryyin Thanks for the response. Sure, I can remove them.. Just checking: You mean I should _ignore_ that particular pylint error (`inconsistent-return-statements`), as just removing the default returns would fail CI again.

And yeah, I completely agree adding any production code should also include tests (unclear how to test this as well).

There are two ways to disable `inconsistent-return-statements`:

1. Globally in `pylintrc`
1. Adding the rule individually in each affected file

What's your preference? For now, I went with option 1 and amended my PR. Please check.

**Comment by terryyin** [comment]
Yes, I think globally is a good idea:-) Thanks!

**Pull request merged**
