### PR TITLE
Add Appveyor CI configurations

### PR DESCRIPTION
**Pull request by rakhimov**
This adds minimal CI configurations for Appveyor-CI with Python 2.7.
Some tests on windows are erring with some filesystem issues:  https://ci.appveyor.com/project/rakhimov/lizard/build/1.0.1

---
This change is [Reviewable](https://reviewable.io/reviews/terryyin/lizard/159)

### CODE REVIEW

**Comment by terryyin** [comment]
Thanks!

**Comment by rakhimov** [comment]
@terryyin You need to setup an appveyor account to get the builds working as Travis.

**Comment by terryyin** [comment]
Let me see ...

**Comment by terryyin** [comment]
Ah, works. Thanks:-) Let me fix them...

**Pull request merged**
