### PR TITLE
get the support for scala

### PR DESCRIPTION
**Pull request by terryyin**

### CODE REVIEW

**Comment by terryyin** [comment]
I've cherry picked the implementation and tests for scala.

It seems the ObjC parameter counting and comments counting are also interesting. I will cherry pick them later.

**Comment by serjant** [comment]
Yeah, but the ObjC comments extracting is still buggy - working on this, need to write a bunch of tests for this one. Also there is a bug in extracting the functions' names in ObjC lang parser

**Comment by terryyin** [comment]
What is the bug?

**Comment by serjant** [comment]
Take a look at the following piece of Obj-C code, it has the declared `- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil` function which contain two parameters nibNameOrNil and nibBundleOrNil, but the tests show that the parameter_count equals to 1 instead of having the value 2:
`
#import "ProcessesViewController.h"
#import "LogsViewController.h"
#import "ProcessesTableViewCell.h"
#import "SystemUtility.h"
#import "Process.h"
#import "MBProgressHUD.h"

@interface ProcessesViewController ()

@end

@implementation ProcessesViewController

@synthesize processesTableView;
@synthesize tableContents;
@synthesize sortedKeys;
@synthesize adView;

- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil {
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        self.title = NSLocalizedString(@"Processes", @"Processes");
        if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad) {
            self.tabBarItem.image = [UIImage imageNamed:@"first@2x"];
        } else {
            self.tabBarItem.image = [UIImage imageNamed:@"first"];
        }
    }

    return self;
}

@end
`

**Pull request closed without merging**
