### PR TITLE
Update xmloutput.py

### PR DESCRIPTION
**Pull request by JiahangLi**
Try to have the summary of the Avg of CCN on a function base, similar to the txt output format.

### CODE REVIEW

**Comment by JiahangLi** [comment]
This build is taking forever. I'm sure there is some issue with it, but I don't know where that occurs.

 What I was trying to do it just change the summary of sum into a summary of average on a function base. (I didn't deleted the sum summary part but mimicked it append the average part to the measure as well.)

I ran my local version and it seems output the right xml results at least but the Jenkins didn't change the text according still.

**Comment by terryyin** [comment]
Thanks:-)

I merged it manually, with a few style improvement.

I know there hasn't been much unit testing for the xmloutput. Is it possible to add some still?

**Comment by terryyin** [comment]
What build? Lizard make or using lizard?

**Comment by JiahangLi** [comment]
Sorry for the late reply. I mean the commit can't pass the CI build thoroughly. It eventually terminated with a job error. 
Big thanks for manually merging it.

I will look into the unit testing later for sure.

I did the try to use CPPNSCC plugin of Jenkins to plot our output.xml, but the table is still printing out the sum CCN and NCSS even after I changed them to average, commented out the sum part as well. The plot is not really giving us information other than function count.(Screenshot attached)
I think it might be some issue of how the plugin interpret with our xml output file. 

plot_ccn
stillsum

**Comment by Coeur** [comment]
@JiahangLi , @terryyin , If this was manually merged, let's close the PR for now. The addition of future unit tests may be tracked as  an "issue" in the meantime if needed.

**Pull request closed without merging**
