### PR TITLE
Add HTML output

### LINKED ISSUE #195: Lizard can not generate Html report???
image

### PR DESCRIPTION
**Pull request by ligurio**
Potentially fixes #195

### CODE REVIEW

**Comment by ligurio** [comment]
Example of HTML report - https://pastebin.com/X5bujJuH

**Comment by terryyin** [comment]
Hi @ligurio is it possible to have some tests?

**Comment by ligurio** [comment]
Yep, will to do a bit later.

**Comment by ligurio** [comment]
Example of HTML report with updated template - https://ligurio.github.io/openbsd-tests/complexity/usr.bin_63.html

**Comment by terryyin** [comment]
Looks great!

**Pull request merged**
