### PR TITLE
Fix unclosed file warning in auto_open

### PR DESCRIPTION
**Pull request by amateurcoffee**
Fix warning such as:
`lizard_ext/auto_open.py:31: ResourceWarning: unclosed file`

### CODE REVIEW

**Comment by amateurcoffee** [comment]
Fixed auto_open test errors

**Comment by amateurcoffee** [comment]
@rakhimov sure, just squashed the commits together.

**Comment by amateurcoffee** [comment]
@rakhimov Would you merge this if you see fit? (I don't have write access)
Please let me know if there is anything needs to be updated.

**Comment by rakhimov** [comment]
Sorry @amateurcoffee , it is up to @terryyin .
I'm just helping him out.
I believe this PR is good to go.

**Comment by terryyin** [comment]
Please allow me a couple of days. In a pretty heavy training process right now.

**Comment by amateurcoffee** [comment]
@terryyin Sure

**Comment by terryyin** [comment]
Though about it a bit, don't know how to write some test for it still.

Thanks any way:-) @amateurcoffee

**Pull request merged**
