### PR TITLE
Add CSV output transform

### PR DESCRIPTION
**Pull request by hallta**
Pretty much what it says: 

Using "--csv" at the command line (I wasn't able to find a logical one-char short switch), will transform the output into CSV.

The output will be identical in structure to the default output, but with some additions: 
* New tokens for each line
* Less verbosity (will not summarize files, will not highlight those that breached a threshold)

### CODE REVIEW

**Comment by terryyin** [comment]
Thanks for the pull request. @hallta do you want add a few tests to the new feature?

**Comment by hallta** [comment]
Definitely. I didn't see any for the xml output so wasn't sure how best to write them. Can you point me to an example I can model the test after?

**Comment by hallta** [comment]
Nevermind :) I've figured out how to test this, and added some new tests.

**Comment by terryyin** [comment]
yeah, the xml output wasn't covered by test, unfortunately. Thanks for having a good start:-)

**Pull request merged**
