### PR TITLE
Fixing bug when python has multiple line for function declaration due to formatting

### PR DESCRIPTION
**Pull request by alyssawangqq**
Currently there's bug in python Lizard when getting LOC and CCN when func declaration has multiple lines. It will only count the function declaration lines but not the implementation. This is because the original code uses indentation to check function ending while for multi-line declaration, the last line will start with ")" with no indent.

Example:
```
def f1(a,
    b
):
  # function implementation for 10 lines
```

Issue in https://github.com/terryyin/lizard/issues/292

### CODE REVIEW

**Comment by terryyin** [comment]
Hi @alyssawangqq thanks for the pull request. Could you please add a test for the scenario?

**Comment by terryyin** [comment]
But the new test is not passing?

**Comment by alyssawangqq** [comment]
@terryyin Sorry just fixed error in test

**Comment by terryyin** [comment]
Thank you very much!

**Pull request merged**
